name: Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build code
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Deployment
        run: echo "Deploying...."


